### ISSUE TITLE
Navigation links mismatch

### ISSUE THREAD

**Issue by ghale5011** [Prakhar-Sapkota69/HostelManagementSystem#1]
There seems to be repetition of same link on navigation bar on both contact and logout buttons.
<body>
    <header class="tm-header">
        <h1 class="logo"><img src="./images/logo.png" alt="Logo" width="100"></h1>
        <nav class="tm-nav">
            <ul class="nav-links">
                <li><a href="homePage.html">Home</a></li>
                <li><a href="aboutus.html">About Us</a></li>
                <li><a href="contact.html">Contact Us</a></li>
                <li><a href="contact.html">Logout</a></li>
            </ul>
        </nav>
    </header>

**Comment by Prakhar-Sapkota69** [comment]
Thank you for pointing it out, I have made the changes accordingly and now it should work as intended.
