### ISSUE TITLE
Database name

### ISSUE THREAD

**Issue by psychpraphool** [Prakhar-Sapkota69/HostelManagementSystem#3]
Write the name of database and tables meaningful so it is understandable by all.
$host = "localhost";
$username = "root";
$password = "";
$database = "main_database";

$conn = new mysqli($host, $username, $password, $database);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

**Comment by Prakhar-Sapkota69** [comment]
Done!
