### ISSUE TITLE
Arrival date highlights automatically

### ISSUE THREAD

**Issue by ghale5011** [Prakhar-Sapkota69/HostelManagementSystem#4]
![Screenshot 2024-05-14 104252](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/127822949/c002dd17-6214-40db-a8df-2eac5b80ebba)
When I am in booking section of user dashboard, the arrival date section of booking form automatically highlights. Please fix it.

**Comment by Prakhar-Sapkota69** [comment]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/165983943/4f14f2bf-ea6d-4aba-9645-4c5ffc9911cc)
Thank you for bringing it to my attention, I fixed the issue and also made the UI more refined.
