### ISSUE TITLE
Nav bar inconsistency

### ISSUE THREAD

**Issue by ghale5011** [Prakhar-Sapkota69/HostelManagementSystem#6]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/127822949/007e60ca-db98-4651-b1c2-e76e981841b7)
The proper css for nav bar is missing on the file of second sprint. Check your repository!

**Comment by Prakhar-Sapkota69** [comment]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/165983943/d770d3bf-1a7a-42ed-a8b9-1ecc084fea57)
Thank you for addressing it, I have made the navigation bar same across all the pages already, It should work fine now.
