### ISSUE TITLE
Heading for contact is misplaced

### ISSUE THREAD

**Issue by ghale5011** [Prakhar-Sapkota69/HostelManagementSystem#7]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/127822949/22677f91-e2e6-4e99-9b79-da17973c71e3)
The heading for contact is not according to wireframes. Place it in the right way accoridng to the wireframe.

**Comment by Prakhar-Sapkota69** [comment]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/165983943/c5cd843e-fc2b-40f9-8902-2225d88f79ff)
Thank you for addressing it, I have updated the CSS to make it look more consistent and adjusted the placement for other items as well.
