### ISSUE TITLE
Colon missing

### ISSUE THREAD

**Issue by ghale5011** [Prakhar-Sapkota69/HostelManagementSystem#8]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/127822949/6dfd3eb5-cc07-45af-9066-1a30384f769f)
Please add colon for email and phone number label.

**Comment by Prakhar-Sapkota69** [comment]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/165983943/13ac2c10-1fd3-49b0-bf14-bc020c910e5f)
Thank you for identifying the error. It was a minor issue that's been fixed already.
