### ISSUE TITLE
Inaccurate gap in login page

### ISSUE THREAD

**Issue by ghale5011** [Prakhar-Sapkota69/HostelManagementSystem#9]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/127822949/da49afae-b523-4f3e-bd7e-70ccd081c89d)
Increase the gap between dropdown box and login button.

**Comment by Prakhar-Sapkota69** [comment]
![image](https://github.com/Prakhar-Sapkota69/HostelManagementSystem/assets/165983943/46ed6093-fdb3-4c1f-b45c-90e3903e8d3c)
Thank you for addressing the issue, It has been fixed.
